name: eryndor-mmo-web-app
region: nyc

domains:
  - domain: eryndor-online.com
    type: PRIMARY
  - domain: www.eryndor-online.com
    type: ALIAS

static_sites:
  - name: web
    github:
      repo: jbuehler23/eryndor-mmo
      branch: main
      deploy_on_push: true

    build_command: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      . $HOME/.cargo/env
      rustup target add wasm32-unknown-unknown

      # Install system dependencies
      apt-get update && apt-get install -y libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      # Install Bevy CLI
      cargo install --git https://github.com/TheBevyFlock/bevy_cli --tag cli-v0.1.0-alpha.2 --locked bevy_cli

      # Build WASM client
      cd crates/eryndor_client
      bevy build --yes --release web --bundle

    output_dir: target/bevy_web/web-release/client

    envs:
      - key: SERVER_IP
        # WebTransport server IP (uses self-signed cert on port 5002)
        # Certificate hash is fetched from http://165.227.217.144:8080/cert
        # Ports default to 5002 (WebTransport) and 8080 (cert server)
        value: 165.227.217.144

    routes:
      - path: /

    cors:
      allow_origins:
        - prefix: https://
      allow_methods:
        - GET
        - POST
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
